### ISSUE TITLE
Provide a way to install without downloading during build?

### ISSUE THREAD

**Issue by swt2c** [cvc5/cvc5_pythonic_api#85]
Would you be willing to provide a way to install the pythonic API without having to download it *during* the build process?

- Can it just be integrated with the main cvc5 repository (since it is required if the Python bindings are enabled)?
- Or, can it be made optional?
- Or, can it be pre-downloaded somewhere (other than the CMAKE_BINARY_DIR)?

**Comment by alex-ozdemir** [comment]
Hi @swt2c ,

Thank you for this question, and I apologize for the delay in our response.
We're not sure we understand what you're looking for. Could you explain more?

Cheers,
Alex

**Comment by swt2c** [comment]
I'm trying to build the pythonic API as part of a Debian package, and we can't download files during the build, so I was looking for an alternative.

**Comment by alex-ozdemir** [comment]
That makes sense! We'll discuss this and try to find a solution for you.

**Comment by alex-ozdemir** [comment]
This has now been [merged](https://github.com/cvc5/cvc5/pull/10188#event-11214095103); the implementation is a configuration option called `--pythonic-path=PATH`, as documented [here](https://github.com/cvc5/cvc5/blob/main/INSTALL.rst#dependencies-for-language-bindings).

I'm going to close the issue for now. Please re-open it if this doesn't meet your needs.
